BEGIN;

ALTER TABLE runs ADD COLUMN type VARCHAR(255);
ALTER TABLE runs ADD COLUMN name VARCHAR(255);

UPDATE runs set type='Run', name='Generic Run';

ALTER TABLE runs ALTER COLUMN type SET NOT NULL;
ALTER TABLE runs ALTER COLUMN name SET NOT NULL;

COMMIT;

