// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: db.sql

package runstore

import (
	"context"
)

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT version, dirty FROM schema_migrations
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (SchemaMigration, error) {
	row := q.db.QueryRow(ctx, getSchemaVersion)
	var i SchemaMigration
	err := row.Scan(&i.Version, &i.Dirty)
	return i, err
}
