// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package runstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Run struct {
	Date     time.Time `json:"date"`
	Distance float64   `json:"distance"`
	Runtime  int32     `json:"runtime"`
}

type SchemaMigration struct {
	Version int32       `json:"version"`
	Dirty   pgtype.Bool `json:"dirty"`
}

type StravaToken struct {
	ID           uuid.UUID `json:"id"`
	AccessToken  string    `json:"access_token"`
	ExpiresAt    int32     `json:"expires_at"`
	RefreshToken string    `json:"refresh_token"`
}

type User struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	StravaToken pgtype.UUID `json:"strava_token"`
}
