// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: strava_tokens.sql

package runstore

import (
	"context"

	"github.com/google/uuid"
)

const getStravaToken = `-- name: GetStravaToken :one
SELECT id, access_token, expires_at, refresh_token FROm strava_tokens WHERE id=$1
`

func (q *Queries) GetStravaToken(ctx context.Context, id uuid.UUID) (StravaToken, error) {
	row := q.db.QueryRow(ctx, getStravaToken, id)
	var i StravaToken
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.RefreshToken,
	)
	return i, err
}
